version: '3.7'
services:
  rest-api:
    container_name: auth-api
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - '4000:4000'
